logement_index:
    path:     /
    defaults: { _controller: "AppBundle:Logement:index" }
    methods:  GET

logement_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Logement:show" }
    methods:  GET

logement_new:
    path:     /new
    defaults: { _controller: "AppBundle:Logement:new" }
    methods:  [GET, POST]

logement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Logement:edit" }
    methods:  [GET, POST]

logement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Logement:delete" }
    methods:  [GET, POST]
